### PR TITLE
Request to merge Views

### PR DESCRIPTION
**Pull request by Kingstalux**
- In this project I added the Views associated with the Models and Controllers that I had already created for my Blog App.
- Made use of partials when adding views.
- Added views accoriding to the wire provided in the requirements.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @Kingstalux ,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Make sure the app renders the users and the posts, right now it's rendering a static page and we should see the users.posts.




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kingstalux** [comment]
Hello @dasileker,
Thanks for the review. The first page (root view) of the blog app displays all the users and to see the posts for a particular user, you've to click on a user which takes you to the second view. Next to see all the posts for a particular user, click on the post which takes you to the third view. Finally to see all the comments for a particular post, click on the post and it takes you to the final view.

**Comment by dasileker** [comment]
> Hello @dasileker, Thanks for the review. The first page (root view) of the blog app displays all the users and to see the posts for a particular user, you've to click on a user which takes you to the second view. Next to see all the posts for a particular user, click on the post which takes you to the third view. Finally to see all the comments for a particular post, click on the post and it takes you to the final view.

hello @Kingstalux

this is what i see after all is set, a blanck page

Capture web_23-2-2022_105214_localhost

**Comment by Kingstalux** [comment]
> > Hello @dasileker, Thanks for the review. The first page (root view) of the blog app displays all the users and to see the posts for a particular user, you've to click on a user which takes you to the second view. Next to see all the posts for a particular user, click on the post which takes you to the third view. Finally to see all the comments for a particular post, click on the post and it takes you to the final view.
> 
> hello @Kingstalux
> 
> this is what i see after all is set, a blanck page
> 
> Capture web_23-2-2022_105214_localhost

Hello @dasileker,
I have cloned the project again and ran bundle install and it displays okay. My ruby version is 2.7.5 and I don't know if that might be the cause but for now I'll just wait for the next reviewer's comments. If he raises the same issue, then the issue will surely be from my end.

**Comment by DeliceLydia** [comment]
Hello @Kingstalux, your project is working well I have added data using
rails console. Good job!

**Review by DeliceLydia — APPROVED** [review]
# Congratulations! 🎉🎉

## Hi @Kingstalux, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
